Delivery.Management.MVC/Controllers/DeliveryAllocationsController.cs
using Delivery.Management.MVC.Contracts;
using Delivery.Management.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Delivery.Management.MVC.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DeliveryAllocationsController : Controller
    {
        private readonly IDeliveryAllocationService _deliveryAllocationRepository;

        public DeliveryAllocationsController(IDeliveryAllocationService deliveryAllocationRepository)
        {
            _deliveryAllocationRepository = deliveryAllocationRepository;
        }

        // GET: DeliveryAllocationsController
        public async Task<ActionResult> Index()
        {
            var model = await _deliveryAllocationRepository.GetDeliveryAllocations();
            return View(model);
        }

        // GET: DeliveryAllocationsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _deliveryAllocationRepository.GetDeliveryAllocationDetails(id);
            return View(model);
        }

        // GET: DeliveryAllocationsController/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: DeliveryAllocationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeliveryAllocationVM deliveryAllocation)
        {
            try
            {
                var response = await _deliveryAllocationRepository.CreateDeliveryAllocation(deliveryAllocation);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryAllocation);
        }

        // GET: DeliveryAllocationsController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _deliveryAllocationRepository.GetDeliveryAllocationDetails(id);
            return View(model);
        }

        // POST: DeliveryAllocationsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DeliveryAllocationVM deliveryAllocation)
        {
            try
            {
                var response = await _deliveryAllocationRepository.UpdateDeliveryAllocation(id, deliveryAllocation);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryAllocation);
        }

        // POST: DeliveryAllocationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var response = await _deliveryAllocationRepository.DeleteDeliveryAllocation(id);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }
    }
}

Delivery.Management.MVC/Controllers/DeliveryRequestsController.cs
using System.Data;
using Delivery.Management.MVC.Contracts;
using Delivery.Management.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Delivery.Management.MVC.Controllers
{
    public class DeliveryRequestsController : Controller
    {
        private readonly IDeliveryRequestService _deliveryRequestRepository;
        private readonly IDeliveryAllocationService _deliveryAllocationRepository;
        private readonly IDeliveryTypeService _deliveryTypeRepository;

        public DeliveryRequestsController(IDeliveryRequestService deliveryRequestRepository, IDeliveryAllocationService deliveryAllocationRepository, IDeliveryTypeService deliveryTypeRepository)
        {
            _deliveryRequestRepository = deliveryRequestRepository;
            _deliveryTypeRepository = deliveryTypeRepository;
            _deliveryAllocationRepository = deliveryAllocationRepository;

        }

        // GET: DeliveryRequestsController
        public async Task<ActionResult> Index()
        {
            var model = await _deliveryRequestRepository.GetDeliveryRequests();
            return View(model);
        }

        // GET: DeliveryRequestsController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _deliveryRequestRepository.GetDeliveryRequestsDetails(id);
            return View(model);
        }

        // GET: DeliveryRequestsController/Create
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: DeliveryRequestsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Create(CreateDeliveryRequestVM deliveryRequest)
        {
            try
            {
                var response = await _deliveryRequestRepository.CreateDeliveryRequest(deliveryRequest);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryRequest);
        }

        // GET: DeliveryRequestsController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _deliveryRequestRepository.GetDeliveryRequestsDetails(id);
            return View(model);
        }

        // POST: DeliveryRequestsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DeliveryRequestVM deliveryRequest)
        {
            try
            {
                var response = await _deliveryRequestRepository.UpdateDeliveryRequest(id, deliveryRequest);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryRequest);
        }


        //POST: DeliveryRequestsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var response = await _deliveryRequestRepository.DeleteDeliveryRequest(id);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }
    }
}

Delivery.Management.MVC/Controllers/DeliveryTypesController.cs
using Delivery.Management.MVC.Contracts;
using Delivery.Management.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Delivery.Management.MVC.Controllers
{
    public class DeliveryTypesController : Controller
    {
        private readonly IDeliveryTypeService _deliveryTypeRepository;

        public DeliveryTypesController(IDeliveryTypeService deliveryTypeRepository)
        {
            _deliveryTypeRepository = deliveryTypeRepository;
        }

        // GET: DeliveryTypesController
        public async Task<ActionResult> Index()
        {
            var model = await _deliveryTypeRepository.GetDeliveryTypes();
            return View(model);
        }

        // GET: DeliveryTypesController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _deliveryTypeRepository.GetDeliveryTypesDetails(id);
            return View(model);
        }

        // GET: DeliveryTypesController/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: DeliveryTypesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeliveryTypeVM deliveryType)
        {
            try
            {
                var response = await _deliveryTypeRepository.CreateDeliveryType(deliveryType);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryType);
        }

        // GET: DeliveryTypesController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _deliveryTypeRepository.GetDeliveryTypesDetails(id);
            return View(model);
        }

        // POST: DeliveryTypesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, DeliveryTypeVM deliveryType)
        {
            try
            {
                var response = await _deliveryTypeRepository.UpdateDeliveryType(id, deliveryType);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(deliveryType);
        }

        // GET: DeliveryTypesController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var response = await _deliveryTypeRepository.DeleteDeliveryType(id);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View();
        }

    }
}

Delivery.Management.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Delivery.Management.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Delivery.Management.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Delivery.Management.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>



                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Employee"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryRequests" asp-action="Index">Requests</a>
                                </li>
                                
                            }
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryAllocations" asp-action="Index">Services</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryTypes" asp-action="Index">Status</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="DeliveryRequests" asp-action="Index">Requests</a>
                                </li>
                            }

                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Delivery.Management.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>